# Generated by Django 4.2.27 on 2026-01-27 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_active_product_description_product_featured_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prize',
            new_name='price',
        ),
    ]
